### ISSUE TITLE
D7.10 Data Management Plan v3 

### ISSUE THREAD

**Issue by p-a-s-c-a-l** [clarity-h2020/ckan#32]
#### Tasks for [D7.10](https://github.com/clarity-h2020/ckan/milestone/2):

- [x] [Perform DMP related Integrity checks](https://github.com/clarity-h2020/ckan/issues/14)
- [x] [Publish Hazard Datasets calculated by ZAMG as Open Data](https://github.com/clarity-h2020/ckan/issues/9)
- [x] [Publish Hazard Local Effects Input Layers as OpenData](https://github.com/clarity-h2020/ckan/issues/31)
- [x] [Automatic Report Generation from CKAN Contents](https://github.com/clarity-h2020/data-management-plan/issues/1)
--- 
#### Update Datasets accordingly ([validation tasks](https://github.com/clarity-h2020/ckan/issues?q=is%3Aissue+is%3Aopen+label%3Avalidation)):

- [x] [Clarity European Data - T2.2 - CKAN Data Collection ](https://github.com/clarity-h2020/ckan/issues/28)
- [x] [DC1 - T2.2 - CKAN Data Collection](https://github.com/clarity-h2020/ckan/issues/24)
- [x] [DC2 - T2.2 - CKAN Data Collection](https://github.com/clarity-h2020/ckan/issues/25)
- [x] [DC3 - T2.2 - CKAN Data Collection](https://github.com/clarity-h2020/ckan/issues/26)
- [x] [DC4 - T2.2 - CKAN Data Collection](https://github.com/clarity-h2020/ckan/issues/27)

**Comment by p-a-s-c-a-l** [comment]
done
