### ISSUE TITLE
Data Management Example: Heatwave Duration Hazard

### ISSUE THREAD

**Issue by p-a-s-c-a-l** [clarity-h2020/ckan#8]
~~Deposit [Tx75p_consecutive_max_EUR-11_ICHEC-EC-EARTH_rcp85_r12i1p1_SMHI-RCA4_v1_day_20110101-20401231_netcdf3.nc](http://repository.atosresearch.eu/owncloud/remote.php/webdav/CLARITY/WP7%20Project%20Management/T7.3%20Data%20Management/example/Tx75p_consecutive_max_EUR-11_ICHEC-EC-EARTH_rcp85_r12i1p1_SMHI-RCA4_v1_day_20110101-20401231_netcdf3.nc) in [Zenodo](https://zenodo.org/communities/clarity/) and~~  create a respective resource entry in [ckan](https://ckan.myclimateservice.eu/) which represent CLARITY's *"living"* [Data Management Plan](https://zenodo.org/record/1491532).

Meta-Data describing the .netcdf file can be found in [Hazard_definitions.docx](http://repository.atosresearch.eu/owncloud/remote.php/webdav/CLARITY/WP7%20Project%20Management/T7.3%20Data%20Management/example/Hazard_definitions.docx)

```json
{
	"indexName": "Heatwave Duration Hazard",
	"indexAbbreviation": "HDH",
	"description": "The hazard of the number of consecutive days with a maximum temperature greater than the 75th percentile of the maximum temperature within the baseline period of 1971-2000 during the warm months April-September.",
	"periodStart": "2011-01-01",
	"periodEnd": "2040-12-31",
	"units": "hazard scale",
	"type": "integer",
	"missingValue": 1.000000e+20,
	"threshold_low": "50%",
	"threshold_high": "100%",
	"comment": "Hazard value 1: increase is less than theshold_low. Hazard value 2: increase is greater than or equal to threshold_low and less than threshold_high. Hazard value 3: increase is greater than threshold_high. The changes are relative to the baseline period 1971-2000.",
	"format": {
		"raster_or_vector": "raster",
		"projection": "WGS84",
		"nx": "345",
		"ny": "351",
		"nt": "1"
	},
	"climateModels": {
		"dataOrigin": "CORDEX Europe 0.11 deg",
		"emissionScenario": "RCP2.6",
		"comment": "The field models shows the models used for the calculation of this climate index. The format is of the form institute_gcm_rcm_version_rip.",
		"models": "CLMcom_CNRM-CERFACS-CNRM-CM5_CLMcom-CCLM4-8-17_v1_r1i1p1, CLMcom_ICHEC-EC-EARTH_CLMcom-CCLM4-8-17_v1_r12i1p1, CLMcom_MOHC-HadGEM2-ES_CLMcom-CCLM4-8-17_v1_r1i1p1, CLMcom_MPI-M-MPI-ESM-LR_CLMcom-CCLM4-8-17_v1_r1i1p1, CNRM_CNRM-CERFACS-CNRM-CM5_CNRM-ALADIN53_v1_r1i1p1, DMI_ICHEC-EC-EARTH_DMI-HIRHAM5_v1_r3i1p1, DMI_NCC-NorESM1-M_DMI-HIRHAM5_v2_r1i1p1, IPSL-INERIS_IPSL-IPSL-CM5A-MR_IPSL-INERIS-WRF331F_v1_r1i1p1, KNMI_ICHEC-EC-EARTH_KNMI-RACMO22E_v1_r12i1p1, SMHI_CNRM-CERFACS-CNRM-CM5_SMHI-RCA4_v1_r1i1p1, SMHI_ICHEC-EC-EARTH_SMHI-RCA4_v1_r12i1p1, SMHI_IPSL-IPSL-CM5A-MR_SMHI-RCA4_v1_r1i1p1, SMHI_MOHC-HadGEM2-ES_SMHI-RCA4_v1_r1i1p1, SMHI_MPI-M-MPI-ESM-LR_SMHI-RCA4_v1_r1i1p1"
	}
}
```

This task depends on
- [x] https://github.com/clarity-h2020/ckan/issues/2 Configure CKAN for CSIS 
- [x] ~https://github.com/clarity-h2020/ckan/issues/4 Support Datasets Relationships~
- [ ] https://github.com/clarity-h2020/ckan/issues/5 Meta-Data Harmonisation

**Comment by maesbri** [comment]
Is this metadata format extracted from the netcdf files or has it been developed ad-hoc? If it is latter, I would strongly suggest to use our data package specification metadata structure, otherwise it is going to be a nightmare with several ways of "metadating" the same resources.

In fact, IMHO CLARITY Data Package should be the way to harmonize all different metadata formats (and data structures) we have in the project.

Btw, I will be taking some attributes ideas from this example to improve our Data Package specification.

**Comment by p-a-s-c-a-l** [comment]
I asked this question about the origin of the JSON meta-data, but didn't get and answer (yet). I invited Astrid and Robert to the join [Science Support Team](https://github.com/orgs/clarity-h2020/teams/science-support-team) to discuss [this issue](https://github.com/clarity-h2020/scenario-analysis/issues/7) about Meta-Data Harmonisation.

**Comment by maesbri** [comment]
Maybe it is time to stop answering tech-related emails and force them to use github if they want to continue the discussion.

**Comment by p-a-s-c-a-l** [comment]
According to https://github.com/clarity-h2020/ckan/issues/9#issuecomment-441967233, the datasets are published on [data.ccca.ac.at](https://data.ccca.ac.at/organization/zamg). So this Example is no longer needed.

**Comment by p-a-s-c-a-l** [comment]
done
